// Build: bundles the packaged-game player, then the editor (which embeds the
// player so "Package Game" works offline and from file://).
//
//   node tools/build.mjs            production build -> app/editor.js
//   node tools/build.mjs --dev      unminified, with sourcemaps
//   node tools/build.mjs --check    fail if app/editor.js is stale
import * as esbuild from 'esbuild';
import { readFileSync, existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const dev = process.argv.includes('--dev');
const check = process.argv.includes('--check');

const common = {
  bundle: true, format: 'iife', target: ['es2020'],
  minify: !dev, legalComments: 'none', logLevel: 'warning', absWorkingDir: root,
};

const t0 = performance.now();
const player = await esbuild.build({ ...common, entryPoints: ['src/player/main.js'], write: false });
const playerCode = player.outputFiles[0].text;

const editor = await esbuild.build({
  ...common,
  entryPoints: ['src/editor/main.js'],
  write: false,
  sourcemap: dev ? 'inline' : false,
  define: { __PLAYER_BUNDLE__: JSON.stringify(playerCode) },
  banner: { js: '/* Spud Engine editor — generated by tools/build.mjs, edit src/ instead */' },
});
const editorCode = editor.outputFiles[0].text;
const out = resolve(root, 'app/editor.js');

if (check) {
  const cur = existsSync(out) ? readFileSync(out, 'utf8') : '';
  if (cur !== editorCode) { console.error('app/editor.js is stale — run `npm run build`'); process.exit(1); }
  console.log('app/editor.js is up to date');
} else {
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, editorCode);
  const kb = (s) => `${(Buffer.byteLength(s) / 1024).toFixed(0)} KB`;
  console.log(`built app/editor.js ${kb(editorCode)} (player runtime ${kb(playerCode)}) in ${Math.round(performance.now() - t0)} ms`);
}
